import type { Card } from '@/features/gameConfig/cardTypes';

const REWARD_CARD_POOL: Card[] = [
  // ═══════════════════════════════════════════════════════════════
  // WARRIOR REWARDS
  // ═══════════════════════════════════════════════════════════════

  // ── Rage ────────────────────────────────────────────────────────
  {
    id: 'w-reckless-strike',
    name: 'Reckless Strike',
    cost: 1,
    trait: 'rage',
    description: 'Deal 12 damage. Take 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Reckless Strike+',
    upgradeDescription: 'Deal 16 damage. Take 3 damage.',
    baseDamage: 12,
    upgradedDamage: 16,
  },
  {
    id: 'w-cleave',
    name: 'Cleave',
    cost: 2,
    trait: 'rage',
    description: 'Deal 10 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Great Cleave',
    upgradeDescription: 'Deal 14 damage to all.',
    baseDamage: 10,
    upgradedDamage: 14,
    isAoe: true,
  },
  {
    id: 'w-fury-chain',
    name: 'Fury Chain',
    cost: 2,
    trait: 'rage',
    description: 'Deal 5 damage ×3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Fury Chain+',
    upgradeDescription: 'Deal 7 damage ×3.',
    baseDamage: 5,
    upgradedDamage: 7,
  },
  {
    id: 'w-savage-swing',
    name: 'Savage Swing',
    cost: 1,
    trait: 'rage',
    description: 'Deal 6 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Savage Swing+',
    upgradeDescription: 'Deal 9 damage. Vuln 1.',
    baseDamage: 6,
    upgradedDamage: 9,
  },
  {
    id: 'w-war-stomp',
    name: 'War Stomp',
    cost: 2,
    trait: 'rage',
    description: 'Deal 8 damage to all. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'War Stomp+',
    upgradeDescription: 'Deal 11 damage to all. Weak 1.',
    baseDamage: 8,
    upgradedDamage: 11,
    isAoe: true,
  },
  {
    id: 'w-execute',
    name: 'Execute',
    cost: 3,
    trait: 'rage',
    description: 'Deal 22 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Execute+',
    upgradeDescription: 'Deal 28 damage.',
    baseDamage: 22,
    upgradedDamage: 28,
    isRare: true,
  },
  {
    id: 'w-rampage',
    name: 'Rampage',
    cost: 3,
    trait: 'rage',
    description: 'Deal 16 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Rampage+',
    upgradeDescription: 'Deal 22 damage to all.',
    baseDamage: 16,
    upgradedDamage: 22,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'w-pummel',
    name: 'Pummel',
    cost: 1,
    trait: 'rage',
    description: 'Deal 4 damage ×2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Pummel+',
    upgradeDescription: 'Deal 6 damage ×2.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 'w-headbutt',
    name: 'Headbutt',
    cost: 0,
    trait: 'rage',
    description: 'Deal 2 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Headbutt+',
    upgradeDescription: 'Deal 4 damage. Weak 1.',
    baseDamage: 2,
    upgradedDamage: 4,
  },
  {
    id: 'w-bloodlust',
    name: 'Bloodlust',
    cost: 2,
    trait: 'rage',
    description: 'Deal 14 damage. Heal 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Bloodlust+',
    upgradeDescription: 'Deal 18 damage. Heal 6.',
    baseDamage: 14,
    upgradedDamage: 18,
    baseHeal: 4,
    upgradedHeal: 6,
  },
  {
    id: 'w-massacre',
    name: 'Massacre',
    cost: 3,
    trait: 'rage',
    description: 'Deal 14 damage to all. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Massacre+',
    upgradeDescription: 'Deal 18 damage to all. Vuln 2.',
    baseDamage: 14,
    upgradedDamage: 18,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'w-charge',
    name: 'Charge',
    cost: 1,
    trait: 'rage',
    description: 'Deal 10 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Charge+',
    upgradeDescription: 'Deal 13 damage. Vuln 1.',
    baseDamage: 10,
    upgradedDamage: 13,
  },

  // ── Iron ────────────────────────────────────────────────────────
  {
    id: 'w-shield-wall',
    name: 'Shield Wall',
    cost: 2,
    trait: 'iron',
    description: 'Gain 10 Block. Persists.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Shield Wall+',
    upgradeDescription: 'Gain 14 Block. Persists.',
    baseBlock: 10,
    upgradedBlock: 14,
  },
  {
    id: 'w-iron-skin',
    name: 'Iron Skin',
    cost: 1,
    trait: 'iron',
    description: 'Gain 5 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Iron Skin+',
    upgradeDescription: 'Gain 7 Block. +3 Thorns.',
    baseBlock: 5,
    upgradedBlock: 7,
  },
  {
    id: 'w-bulwark',
    name: 'Bulwark',
    cost: 3,
    trait: 'iron',
    description: 'Gain 18 Block. +3 Thorns.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Great Bulwark',
    upgradeDescription: 'Gain 24 Block. +4 Thorns.',
    baseBlock: 18,
    upgradedBlock: 24,
    isRare: true,
  },
  {
    id: 'w-parry',
    name: 'Parry',
    cost: 1,
    trait: 'iron',
    description: 'Gain 4 Block. Deal 4 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Parry+',
    upgradeDescription: 'Gain 6 Block. Deal 6 damage.',
    baseBlock: 4,
    upgradedBlock: 6,
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 'w-shield-bash',
    name: 'Shield Bash',
    cost: 1,
    trait: 'iron',
    description: 'Gain 3 Block. Deal 6 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Shield Bash+',
    upgradeDescription: 'Gain 5 Block. Deal 8 damage.',
    baseBlock: 3,
    upgradedBlock: 5,
    baseDamage: 6,
    upgradedDamage: 8,
  },
  {
    id: 'w-sentinel',
    name: 'Sentinel',
    cost: 2,
    trait: 'iron',
    description: 'Gain 8 Block. Heal 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Sentinel+',
    upgradeDescription: 'Gain 11 Block. Heal 6.',
    baseBlock: 8,
    upgradedBlock: 11,
    baseHeal: 4,
    upgradedHeal: 6,
  },
  {
    id: 'w-reinforce',
    name: 'Reinforce',
    cost: 0,
    trait: 'iron',
    description: 'Gain 2 Block. +1 Regen.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Reinforce+',
    upgradeDescription: 'Gain 4 Block. +1 Regen.',
    baseBlock: 2,
    upgradedBlock: 4,
  },
  {
    id: 'w-stone-form',
    name: 'Stone Form',
    cost: 3,
    trait: 'iron',
    description: 'Gain 20 Block. Persists.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Stone Form+',
    upgradeDescription: 'Gain 26 Block. Persists.',
    baseBlock: 20,
    upgradedBlock: 26,
    isRare: true,
  },
  {
    id: 'w-counter-strike',
    name: 'Counter Strike',
    cost: 2,
    trait: 'iron',
    description: 'Gain 6 Block. Deal 8 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Counter Strike+',
    upgradeDescription: 'Gain 8 Block. Deal 11 damage.',
    baseBlock: 6,
    upgradedBlock: 8,
    baseDamage: 8,
    upgradedDamage: 11,
  },
  {
    id: 'w-deflect',
    name: 'Deflect',
    cost: 1,
    trait: 'iron',
    description: 'Gain 6 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Deflect+',
    upgradeDescription: 'Gain 9 Block.',
    baseBlock: 6,
    upgradedBlock: 9,
  },
  {
    id: 'w-aegis',
    name: 'Aegis',
    cost: 2,
    trait: 'iron',
    description: 'Gain 14 Block.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Aegis+',
    upgradeDescription: 'Gain 18 Block.',
    baseBlock: 14,
    upgradedBlock: 18,
  },
  {
    id: 'w-last-stand',
    name: 'Last Stand',
    cost: 3,
    trait: 'iron',
    description: 'Gain 16 Block. Deal 10 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Last Stand+',
    upgradeDescription: 'Gain 20 Block. Deal 14 damage.',
    baseBlock: 16,
    upgradedBlock: 20,
    baseDamage: 10,
    upgradedDamage: 14,
    isRare: true,
  },

  // ── Blood ───────────────────────────────────────────────────────
  {
    id: 'w-leech',
    name: 'Leech',
    cost: 1,
    trait: 'blood',
    description: 'Deal 4 damage. Heal 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Leech+',
    upgradeDescription: 'Deal 6 damage. Heal 6.',
    baseDamage: 4,
    upgradedDamage: 6,
    baseHeal: 4,
    upgradedHeal: 6,
  },
  {
    id: 'w-crimson-slash',
    name: 'Crimson Slash',
    cost: 1,
    trait: 'blood',
    description: 'Deal 7 damage. Heal 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Crimson Slash+',
    upgradeDescription: 'Deal 10 damage. Heal 3.',
    baseDamage: 7,
    upgradedDamage: 10,
    baseHeal: 2,
    upgradedHeal: 3,
  },
  {
    id: 'w-transfusion',
    name: 'Transfusion',
    cost: 2,
    trait: 'blood',
    description: 'Heal 10.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Transfusion+',
    upgradeDescription: 'Heal 14.',
    baseHeal: 10,
    upgradedHeal: 14,
  },
  {
    id: 'w-blood-shield',
    name: 'Blood Shield',
    cost: 1,
    trait: 'blood',
    description: 'Gain 4 Block. Heal 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Blood Shield+',
    upgradeDescription: 'Gain 6 Block. Heal 5.',
    baseBlock: 4,
    upgradedBlock: 6,
    baseHeal: 3,
    upgradedHeal: 5,
  },
  {
    id: 'w-vampiric-touch',
    name: 'Vampiric Touch',
    cost: 2,
    trait: 'blood',
    description: 'Deal 6 damage. Heal 6. +1 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Vampiric Touch+',
    upgradeDescription: 'Deal 9 damage. Heal 9. +1 Regen.',
    baseDamage: 6,
    upgradedDamage: 9,
    baseHeal: 6,
    upgradedHeal: 9,
  },
  {
    id: 'w-hemorrhage',
    name: 'Hemorrhage',
    cost: 2,
    trait: 'blood',
    description: 'Deal 10 damage. Burn 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Hemorrhage+',
    upgradeDescription: 'Deal 14 damage. Burn 6.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseBurn: 4,
    upgradedBurn: 6,
  },
  {
    id: 'w-life-tap',
    name: 'Life Tap',
    cost: 0,
    trait: 'blood',
    description: 'Heal 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Life Tap+',
    upgradeDescription: 'Heal 5.',
    baseHeal: 3,
    upgradedHeal: 5,
  },
  {
    id: 'w-blood-rage',
    name: 'Blood Rage',
    cost: 3,
    trait: 'blood',
    description: 'Deal 14 damage. Heal 8.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Blood Rage+',
    upgradeDescription: 'Deal 18 damage. Heal 12.',
    baseDamage: 14,
    upgradedDamage: 18,
    baseHeal: 8,
    upgradedHeal: 12,
    isRare: true,
  },
  {
    id: 'w-crimson-wave',
    name: 'Crimson Wave',
    cost: 3,
    trait: 'blood',
    description: 'Deal 10 damage to all. Heal 6.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Crimson Wave+',
    upgradeDescription: 'Deal 14 damage to all. Heal 8.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseHeal: 6,
    upgradedHeal: 8,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'w-mend-wounds',
    name: 'Mend Wounds',
    cost: 1,
    trait: 'blood',
    description: 'Heal 6.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Mend Wounds+',
    upgradeDescription: 'Heal 9.',
    baseHeal: 6,
    upgradedHeal: 9,
  },
  {
    id: 'w-blood-oath',
    name: 'Blood Oath',
    cost: 2,
    trait: 'blood',
    description: 'Gain 5 Block. Heal 5. +1 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Blood Oath+',
    upgradeDescription: 'Gain 7 Block. Heal 8. +1 Regen.',
    baseBlock: 5,
    upgradedBlock: 7,
    baseHeal: 5,
    upgradedHeal: 8,
  },
  {
    id: 'w-sanguine-burst',
    name: 'Sanguine Burst',
    cost: 3,
    trait: 'blood',
    description: 'Deal 12 damage. Heal 12.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Sanguine Burst+',
    upgradeDescription: 'Deal 16 damage. Heal 16.',
    baseDamage: 12,
    upgradedDamage: 16,
    baseHeal: 12,
    upgradedHeal: 16,
    isRare: true,
  },

  // ── Thunder ─────────────────────────────────────────────────────
  {
    id: 'w-thunderclap',
    name: 'Thunderclap',
    cost: 2,
    trait: 'thunder',
    description: 'Deal 8 damage to all. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Thunderclap+',
    upgradeDescription: 'Deal 11 damage to all. Weak 1.',
    baseDamage: 8,
    upgradedDamage: 11,
    isAoe: true,
  },
  {
    id: 'w-chain-lightning',
    name: 'Chain Lightning',
    cost: 2,
    trait: 'thunder',
    description: 'Deal 6 damage ×2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Chain Lightning+',
    upgradeDescription: 'Deal 9 damage ×2.',
    baseDamage: 6,
    upgradedDamage: 9,
  },
  {
    id: 'w-storm-call',
    name: 'Storm Call',
    cost: 3,
    trait: 'thunder',
    description: 'Deal 14 damage to all. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Storm Call+',
    upgradeDescription: 'Deal 18 damage to all. Vuln 2.',
    baseDamage: 14,
    upgradedDamage: 18,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'w-static',
    name: 'Static',
    cost: 1,
    trait: 'thunder',
    description: 'Deal 4 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Static+',
    upgradeDescription: 'Deal 6 damage. Weak 2.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 'w-overcharge',
    name: 'Overcharge',
    cost: 1,
    trait: 'thunder',
    description: 'Deal 8 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Overcharge+',
    upgradeDescription: 'Deal 11 damage.',
    baseDamage: 8,
    upgradedDamage: 11,
  },
  {
    id: 'w-tempest',
    name: 'Tempest',
    cost: 3,
    trait: 'thunder',
    description: 'Deal 16 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Tempest+',
    upgradeDescription: 'Deal 22 damage to all.',
    baseDamage: 16,
    upgradedDamage: 22,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'w-jolt',
    name: 'Jolt',
    cost: 0,
    trait: 'thunder',
    description: 'Deal 3 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Jolt+',
    upgradeDescription: 'Deal 5 damage. Vuln 1.',
    baseDamage: 3,
    upgradedDamage: 5,
  },
  {
    id: 'w-surge',
    name: 'Surge',
    cost: 1,
    trait: 'thunder',
    description: 'Deal 5 damage. Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Surge+',
    upgradeDescription: 'Deal 7 damage. Gain 5 Block.',
    baseDamage: 5,
    upgradedDamage: 7,
    baseBlock: 3,
    upgradedBlock: 5,
  },
  {
    id: 'w-arc-flash',
    name: 'Arc Flash',
    cost: 2,
    trait: 'thunder',
    description: 'Deal 10 damage. Weak 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Arc Flash+',
    upgradeDescription: 'Deal 14 damage. Weak 2.',
    baseDamage: 10,
    upgradedDamage: 14,
  },
  {
    id: 'w-disrupt',
    name: 'Disrupt',
    cost: 1,
    trait: 'thunder',
    description: 'Vuln 2. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Disrupt+',
    upgradeDescription: 'Deal 3 damage. Vuln 2. Weak 1.',
    baseDamage: 0,
    upgradedDamage: 3,
  },
  {
    id: 'w-thunder-wave',
    name: 'Thunder Wave',
    cost: 2,
    trait: 'thunder',
    description: 'Deal 6 damage to all. Vuln 1. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Thunder Wave+',
    upgradeDescription: 'Deal 9 damage to all. Vuln 1. Weak 1.',
    baseDamage: 6,
    upgradedDamage: 9,
    isAoe: true,
  },
  {
    id: 'w-cataclysm',
    name: 'Cataclysm',
    cost: 3,
    trait: 'thunder',
    description: 'Deal 20 damage. Vuln 2. Weak 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Cataclysm+',
    upgradeDescription: 'Deal 26 damage. Vuln 2. Weak 2.',
    baseDamage: 20,
    upgradedDamage: 26,
    isRare: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // SAGE REWARDS
  // ═══════════════════════════════════════════════════════════════

  // ── Fire ────────────────────────────────────────────────────────
  {
    id: 's-scorch',
    name: 'Scorch',
    cost: 1,
    trait: 'fire',
    description: 'Deal 5 damage. Burn 5.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Scorch+',
    upgradeDescription: 'Deal 8 damage. Burn 8.',
    baseDamage: 5,
    upgradedDamage: 8,
    baseBurn: 5,
    upgradedBurn: 8,
  },
  {
    id: 's-ignite',
    name: 'Ignite',
    cost: 1,
    trait: 'fire',
    description: 'Burn 6.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ignite+',
    upgradeDescription: 'Burn 9.',
    baseBurn: 6,
    upgradedBurn: 9,
  },
  {
    id: 's-inferno',
    name: 'Inferno',
    cost: 3,
    trait: 'fire',
    description: 'Deal 14 damage to all. Burn 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Inferno+',
    upgradeDescription: 'Deal 18 damage to all. Burn 6.',
    baseDamage: 14,
    upgradedDamage: 18,
    baseBurn: 4,
    upgradedBurn: 6,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-sear',
    name: 'Sear',
    cost: 0,
    trait: 'fire',
    description: 'Burn 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Sear+',
    upgradeDescription: 'Burn 7.',
    baseBurn: 4,
    upgradedBurn: 7,
  },
  {
    id: 's-flame-lance',
    name: 'Flame Lance',
    cost: 2,
    trait: 'fire',
    description: 'Deal 16 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Flame Lance+',
    upgradeDescription: 'Deal 22 damage.',
    baseDamage: 16,
    upgradedDamage: 22,
  },
  {
    id: 's-combustion',
    name: 'Combustion',
    cost: 2,
    trait: 'fire',
    description: 'Deal 8 damage. Burn 8.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Combustion+',
    upgradeDescription: 'Deal 11 damage. Burn 12.',
    baseDamage: 8,
    upgradedDamage: 11,
    baseBurn: 8,
    upgradedBurn: 12,
  },
  {
    id: 's-ember',
    name: 'Ember',
    cost: 0,
    trait: 'fire',
    description: 'Deal 2 damage. Burn 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ember+',
    upgradeDescription: 'Deal 3 damage. Burn 4.',
    baseDamage: 2,
    upgradedDamage: 3,
    baseBurn: 2,
    upgradedBurn: 4,
  },
  {
    id: 's-blaze',
    name: 'Blaze',
    cost: 1,
    trait: 'fire',
    description: 'Deal 10 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Blaze+',
    upgradeDescription: 'Deal 14 damage.',
    baseDamage: 10,
    upgradedDamage: 14,
  },
  {
    id: 's-eruption',
    name: 'Eruption',
    cost: 3,
    trait: 'fire',
    description: 'Deal 18 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Eruption+',
    upgradeDescription: 'Deal 24 damage to all.',
    baseDamage: 18,
    upgradedDamage: 24,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-immolate',
    name: 'Immolate',
    cost: 2,
    trait: 'fire',
    description: 'Deal 6 damage. Burn 10.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Immolate+',
    upgradeDescription: 'Deal 9 damage. Burn 14.',
    baseDamage: 6,
    upgradedDamage: 9,
    baseBurn: 10,
    upgradedBurn: 14,
  },
  {
    id: 's-fire-shield',
    name: 'Fire Shield',
    cost: 1,
    trait: 'fire',
    description: 'Gain 4 Block. Burn 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Fire Shield+',
    upgradeDescription: 'Gain 6 Block. Burn 5.',
    baseBlock: 4,
    upgradedBlock: 6,
    baseBurn: 3,
    upgradedBurn: 5,
  },
  {
    id: 's-pyroclasm',
    name: 'Pyroclasm',
    cost: 3,
    trait: 'fire',
    description: 'Deal 22 damage. Burn 6.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Pyroclasm+',
    upgradeDescription: 'Deal 28 damage. Burn 10.',
    baseDamage: 22,
    upgradedDamage: 28,
    baseBurn: 6,
    upgradedBurn: 10,
    isRare: true,
  },

  // ── Frost ───────────────────────────────────────────────────────
  {
    id: 's-freeze',
    name: 'Freeze',
    cost: 1,
    trait: 'frost',
    description: 'Vuln 2. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Freeze+',
    upgradeDescription: 'Vuln 3. Weak 2.',
  },
  {
    id: 's-glacial-armor',
    name: 'Glacial Armor',
    cost: 2,
    trait: 'frost',
    description: 'Gain 12 Block.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Glacial Armor+',
    upgradeDescription: 'Gain 16 Block.',
    baseBlock: 12,
    upgradedBlock: 16,
  },
  {
    id: 's-ice-lance',
    name: 'Ice Lance',
    cost: 1,
    trait: 'frost',
    description: 'Deal 8 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ice Lance+',
    upgradeDescription: 'Deal 11 damage.',
    baseDamage: 8,
    upgradedDamage: 11,
  },
  {
    id: 's-frostbite',
    name: 'Frostbite',
    cost: 1,
    trait: 'frost',
    description: 'Deal 4 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Frostbite+',
    upgradeDescription: 'Deal 6 damage. Vuln 2.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 's-avalanche',
    name: 'Avalanche',
    cost: 3,
    trait: 'frost',
    description: 'Deal 12 damage to all. Vuln 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Avalanche+',
    upgradeDescription: 'Deal 16 damage to all. Vuln 2.',
    baseDamage: 12,
    upgradedDamage: 16,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-permafrost',
    name: 'Permafrost',
    cost: 2,
    trait: 'frost',
    description: 'Gain 10 Block. Persists.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Permafrost+',
    upgradeDescription: 'Gain 14 Block. Persists.',
    baseBlock: 10,
    upgradedBlock: 14,
  },
  {
    id: 's-shatter',
    name: 'Shatter',
    cost: 2,
    trait: 'frost',
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Shatter+',
    upgradeDescription: 'Deal 18 damage.',
    baseDamage: 14,
    upgradedDamage: 18,
  },
  {
    id: 's-cold-snap',
    name: 'Cold Snap',
    cost: 0,
    trait: 'frost',
    description: 'Weak 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Cold Snap+',
    upgradeDescription: 'Weak 3.',
  },
  {
    id: 's-ice-wall',
    name: 'Ice Wall',
    cost: 2,
    trait: 'frost',
    description: 'Gain 8 Block. Weak 1 to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Ice Wall+',
    upgradeDescription: 'Gain 11 Block. Weak 1 to all.',
    baseBlock: 8,
    upgradedBlock: 11,
    isAoe: true,
  },
  {
    id: 's-crystallize',
    name: 'Crystallize',
    cost: 1,
    trait: 'frost',
    description: 'Gain 6 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Crystallize+',
    upgradeDescription: 'Gain 8 Block. +3 Thorns.',
    baseBlock: 6,
    upgradedBlock: 8,
  },
  {
    id: 's-absolute-zero',
    name: 'Absolute Zero',
    cost: 3,
    trait: 'frost',
    description: 'Deal 8 damage to all. Vuln 2. Weak 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Absolute Zero+',
    upgradeDescription: 'Deal 12 damage to all. Vuln 2. Weak 2.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-glacial-spike',
    name: 'Glacial Spike',
    cost: 3,
    trait: 'frost',
    description: 'Deal 20 damage. Weak 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Glacial Spike+',
    upgradeDescription: 'Deal 26 damage. Weak 2.',
    baseDamage: 20,
    upgradedDamage: 26,
    isRare: true,
  },

  // ── Storm ───────────────────────────────────────────────────────
  {
    id: 's-chain-spark',
    name: 'Chain Spark',
    cost: 1,
    trait: 'storm',
    description: 'Deal 4 damage ×2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Chain Spark+',
    upgradeDescription: 'Deal 6 damage ×2.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 's-lightning-rod',
    name: 'Lightning Rod',
    cost: 1,
    trait: 'storm',
    description: 'Deal 6 damage. Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Lightning Rod+',
    upgradeDescription: 'Deal 8 damage. Gain 5 Block.',
    baseDamage: 6,
    upgradedDamage: 8,
    baseBlock: 3,
    upgradedBlock: 5,
  },
  {
    id: 's-ball-lightning',
    name: 'Ball Lightning',
    cost: 2,
    trait: 'storm',
    description: 'Deal 10 damage. Burn 3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Ball Lightning+',
    upgradeDescription: 'Deal 14 damage. Burn 5.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseBurn: 3,
    upgradedBurn: 5,
  },
  {
    id: 's-shock-wave',
    name: 'Shock Wave',
    cost: 2,
    trait: 'storm',
    description: 'Deal 8 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Shock Wave+',
    upgradeDescription: 'Deal 12 damage to all.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
  },
  {
    id: 's-galvanize',
    name: 'Galvanize',
    cost: 1,
    trait: 'storm',
    description: 'Deal 5 damage. Gain 5 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Galvanize+',
    upgradeDescription: 'Deal 7 damage. Gain 7 Block.',
    baseDamage: 5,
    upgradedDamage: 7,
    baseBlock: 5,
    upgradedBlock: 7,
  },
  {
    id: 's-storm-surge',
    name: 'Storm Surge',
    cost: 3,
    trait: 'storm',
    description: 'Deal 18 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Storm Surge+',
    upgradeDescription: 'Deal 24 damage.',
    baseDamage: 18,
    upgradedDamage: 24,
    isRare: true,
  },
  {
    id: 's-electrocute',
    name: 'Electrocute',
    cost: 2,
    trait: 'storm',
    description: 'Deal 12 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Electrocute+',
    upgradeDescription: 'Deal 16 damage. Vuln 1.',
    baseDamage: 12,
    upgradedDamage: 16,
  },
  {
    id: 's-static-charge',
    name: 'Static Charge',
    cost: 0,
    trait: 'storm',
    description: 'Deal 2 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Static Charge+',
    upgradeDescription: 'Deal 4 damage. Vuln 1.',
    baseDamage: 2,
    upgradedDamage: 4,
  },
  {
    id: 's-thunder-bolt',
    name: 'Thunder Bolt',
    cost: 1,
    trait: 'storm',
    description: 'Deal 10 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Thunder Bolt+',
    upgradeDescription: 'Deal 13 damage.',
    baseDamage: 10,
    upgradedDamage: 13,
  },
  {
    id: 's-overload',
    name: 'Overload',
    cost: 3,
    trait: 'storm',
    description: 'Deal 14 damage to all. Burn 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Overload+',
    upgradeDescription: 'Deal 18 damage to all. Burn 6.',
    baseDamage: 14,
    upgradedDamage: 18,
    baseBurn: 4,
    upgradedBurn: 6,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-spark-storm',
    name: 'Spark Storm',
    cost: 2,
    trait: 'storm',
    description: 'Deal 4 damage ×3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Spark Storm+',
    upgradeDescription: 'Deal 6 damage ×3.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 's-megavolt',
    name: 'Megavolt',
    cost: 3,
    trait: 'storm',
    description: 'Deal 24 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Megavolt+',
    upgradeDescription: 'Deal 30 damage.',
    baseDamage: 24,
    upgradedDamage: 30,
    isRare: true,
  },

  // ── Arcane ──────────────────────────────────────────────────────
  {
    id: 's-dispel',
    name: 'Dispel',
    cost: 1,
    trait: 'arcane',
    description: 'Weak 2. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Dispel+',
    upgradeDescription: 'Weak 3. Vuln 2.',
  },
  {
    id: 's-arcane-ward',
    name: 'Arcane Ward',
    cost: 1,
    trait: 'arcane',
    description: 'Gain 6 Block. Heal 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Arcane Ward+',
    upgradeDescription: 'Gain 8 Block. Heal 4.',
    baseBlock: 6,
    upgradedBlock: 8,
    baseHeal: 2,
    upgradedHeal: 4,
  },
  {
    id: 's-mana-burst',
    name: 'Mana Burst',
    cost: 2,
    trait: 'arcane',
    description: 'Deal 10 damage. Gain 4 Block.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Mana Burst+',
    upgradeDescription: 'Deal 14 damage. Gain 6 Block.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseBlock: 4,
    upgradedBlock: 6,
  },
  {
    id: 's-mystic-pulse',
    name: 'Mystic Pulse',
    cost: 2,
    trait: 'arcane',
    description: 'Deal 8 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Mystic Pulse+',
    upgradeDescription: 'Deal 12 damage to all.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
  },
  {
    id: 's-enchant',
    name: 'Enchant',
    cost: 1,
    trait: 'arcane',
    description: 'Gain 4 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Enchant+',
    upgradeDescription: 'Gain 6 Block. +3 Thorns.',
    baseBlock: 4,
    upgradedBlock: 6,
  },
  {
    id: 's-arcane-storm',
    name: 'Arcane Storm',
    cost: 3,
    trait: 'arcane',
    description: 'Deal 16 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Arcane Storm+',
    upgradeDescription: 'Deal 22 damage to all.',
    baseDamage: 16,
    upgradedDamage: 22,
    isAoe: true,
    isRare: true,
  },
  {
    id: 's-counterspell',
    name: 'Counterspell',
    cost: 0,
    trait: 'arcane',
    description: 'Gain 4 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Counterspell+',
    upgradeDescription: 'Gain 6 Block.',
    baseBlock: 4,
    upgradedBlock: 6,
  },
  {
    id: 's-transmute',
    name: 'Transmute',
    cost: 1,
    trait: 'arcane',
    description: 'Deal 5 damage. Heal 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Transmute+',
    upgradeDescription: 'Deal 7 damage. Heal 5.',
    baseDamage: 5,
    upgradedDamage: 7,
    baseHeal: 3,
    upgradedHeal: 5,
  },
  {
    id: 's-phase-shift',
    name: 'Phase Shift',
    cost: 2,
    trait: 'arcane',
    description: 'Gain 10 Block. Heal 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Phase Shift+',
    upgradeDescription: 'Gain 14 Block. Heal 6.',
    baseBlock: 10,
    upgradedBlock: 14,
    baseHeal: 4,
    upgradedHeal: 6,
  },
  {
    id: 's-arcane-barrage',
    name: 'Arcane Barrage',
    cost: 2,
    trait: 'arcane',
    description: 'Deal 5 damage ×3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Arcane Barrage+',
    upgradeDescription: 'Deal 7 damage ×3.',
    baseDamage: 5,
    upgradedDamage: 7,
  },
  {
    id: 's-annihilate',
    name: 'Annihilate',
    cost: 3,
    trait: 'arcane',
    description: 'Deal 22 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Annihilate+',
    upgradeDescription: 'Deal 28 damage.',
    baseDamage: 22,
    upgradedDamage: 28,
    isRare: true,
  },
  {
    id: 's-cosmic-ray',
    name: 'Cosmic Ray',
    cost: 3,
    trait: 'arcane',
    description: 'Deal 12 damage to all. Vuln 1. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Cosmic Ray+',
    upgradeDescription: 'Deal 16 damage to all. Vuln 2. Weak 1.',
    baseDamage: 12,
    upgradedDamage: 16,
    isAoe: true,
    isRare: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // RANGER REWARDS
  // ═══════════════════════════════════════════════════════════════

  // ── Shadow ──────────────────────────────────────────────────────
  {
    id: 'r-backstab',
    name: 'Backstab',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 10 damage. +5 if Vuln.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Assassinate',
    upgradeDescription: 'Deal 14 damage. +8 if Vuln.',
    baseDamage: 10,
    upgradedDamage: 14,
  },
  {
    id: 'r-poison-edge',
    name: 'Poison Edge',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 5 damage. Weak 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Venom Edge',
    upgradeDescription: 'Deal 7 damage. Weak 3.',
    baseDamage: 5,
    upgradedDamage: 7,
  },
  {
    id: 'r-death-sentence',
    name: 'Death Sentence',
    cost: 3,
    trait: 'shadow',
    description: 'Deal 20 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Execution',
    upgradeDescription: 'Deal 26 damage.',
    baseDamage: 20,
    upgradedDamage: 26,
    isRare: true,
  },
  {
    id: 'r-expose',
    name: 'Expose',
    cost: 1,
    trait: 'shadow',
    description: 'Vuln 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Expose+',
    upgradeDescription: 'Vuln 3.',
  },
  {
    id: 'r-cripple',
    name: 'Cripple',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 6 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Cripple+',
    upgradeDescription: 'Deal 9 damage. Weak 2.',
    baseDamage: 6,
    upgradedDamage: 9,
  },
  {
    id: 'r-shadow-strike',
    name: 'Shadow Strike',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 14 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Shadow Strike+',
    upgradeDescription: 'Deal 18 damage. Vuln 1.',
    baseDamage: 14,
    upgradedDamage: 18,
  },
  {
    id: 'r-cheap-shot',
    name: 'Cheap Shot',
    cost: 0,
    trait: 'shadow',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Cheap Shot+',
    upgradeDescription: 'Deal 5 damage.',
    baseDamage: 3,
    upgradedDamage: 5,
  },
  {
    id: 'r-eviscerate',
    name: 'Eviscerate',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 8 damage. Vuln 1. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Eviscerate+',
    upgradeDescription: 'Deal 12 damage. Vuln 1. Weak 1.',
    baseDamage: 8,
    upgradedDamage: 12,
  },
  {
    id: 'r-assassinate',
    name: 'Assassinate',
    cost: 3,
    trait: 'shadow',
    description: 'Deal 24 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Assassinate+',
    upgradeDescription: 'Deal 30 damage.',
    baseDamage: 24,
    upgradedDamage: 30,
    isRare: true,
  },
  {
    id: 'r-feint',
    name: 'Feint',
    cost: 1,
    trait: 'shadow',
    description: 'Gain 4 Block. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Feint+',
    upgradeDescription: 'Gain 6 Block. Vuln 2.',
    baseBlock: 4,
    upgradedBlock: 6,
  },
  {
    id: 'r-garrote',
    name: 'Garrote',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 6 damage. Weak 2. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Garrote+',
    upgradeDescription: 'Deal 9 damage. Weak 2. Vuln 2.',
    baseDamage: 6,
    upgradedDamage: 9,
  },
  {
    id: 'r-smoke-bomb',
    name: 'Smoke Bomb',
    cost: 3,
    trait: 'shadow',
    description: 'Deal 8 damage to all. Weak 2. Vuln 2.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Smoke Bomb+',
    upgradeDescription: 'Deal 12 damage to all. Weak 2. Vuln 2.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
    isRare: true,
  },

  // ── Nature ──────────────────────────────────────────────────────
  {
    id: 'r-mend',
    name: 'Mend',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Mend+',
    upgradeDescription: 'Heal 10.',
    baseHeal: 6,
    upgradedHeal: 10,
  },
  {
    id: 'r-bramble-wall',
    name: 'Bramble Wall',
    cost: 1,
    trait: 'nature',
    description: 'Gain 5 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Bramble Wall+',
    upgradeDescription: 'Gain 8 Block. +3 Thorns.',
    baseBlock: 5,
    upgradedBlock: 8,
  },
  {
    id: 'r-natures-wrath',
    name: "Nature's Wrath",
    cost: 3,
    trait: 'nature',
    description: 'Deal 12 damage. Heal 8.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: "Nature's Fury",
    upgradeDescription: 'Deal 18 damage. Heal 12.',
    baseDamage: 12,
    upgradedDamage: 18,
    baseHeal: 8,
    upgradedHeal: 12,
    isRare: true,
  },
  {
    id: 'r-thorn-burst',
    name: 'Thorn Burst',
    cost: 2,
    trait: 'nature',
    description: 'Deal 6 damage to all. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Thorn Burst+',
    upgradeDescription: 'Deal 9 damage to all. +3 Thorns.',
    baseDamage: 6,
    upgradedDamage: 9,
    isAoe: true,
  },
  {
    id: 'r-rejuvenate',
    name: 'Rejuvenate',
    cost: 2,
    trait: 'nature',
    description: 'Heal 10. +2 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Rejuvenate+',
    upgradeDescription: 'Heal 14. +2 Regen.',
    baseHeal: 10,
    upgradedHeal: 14,
  },
  {
    id: 'r-bark-skin',
    name: 'Bark Skin',
    cost: 1,
    trait: 'nature',
    description: 'Gain 6 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Bark Skin+',
    upgradeDescription: 'Gain 9 Block.',
    baseBlock: 6,
    upgradedBlock: 9,
  },
  {
    id: 'r-life-bloom',
    name: 'Life Bloom',
    cost: 0,
    trait: 'nature',
    description: 'Heal 2. +1 Regen.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Life Bloom+',
    upgradeDescription: 'Heal 4. +1 Regen.',
    baseHeal: 2,
    upgradedHeal: 4,
  },
  {
    id: 'r-entangle',
    name: 'Entangle',
    cost: 1,
    trait: 'nature',
    description: 'Deal 3 damage. Weak 1. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Entangle+',
    upgradeDescription: 'Deal 5 damage. Weak 1. Vuln 1.',
    baseDamage: 3,
    upgradedDamage: 5,
  },
  {
    id: 'r-wild-growth',
    name: 'Wild Growth',
    cost: 2,
    trait: 'nature',
    description: 'Gain 8 Block. Heal 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Wild Growth+',
    upgradeDescription: 'Gain 11 Block. Heal 6.',
    baseBlock: 8,
    upgradedBlock: 11,
    baseHeal: 4,
    upgradedHeal: 6,
  },
  {
    id: 'r-forests-embrace',
    name: "Forest's Embrace",
    cost: 3,
    trait: 'nature',
    description: 'Gain 14 Block. Heal 10.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: "Forest's Embrace+",
    upgradeDescription: 'Gain 18 Block. Heal 14.',
    baseBlock: 14,
    upgradedBlock: 18,
    baseHeal: 10,
    upgradedHeal: 14,
    isRare: true,
  },
  {
    id: 'r-seed-of-life',
    name: 'Seed of Life',
    cost: 2,
    trait: 'nature',
    description: 'Heal 6. +2 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Seed of Life+',
    upgradeDescription: 'Heal 10. +2 Regen.',
    baseHeal: 6,
    upgradedHeal: 10,
  },
  {
    id: 'r-world-bloom',
    name: 'World Bloom',
    cost: 3,
    trait: 'nature',
    description: 'Heal 14. +2 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'World Bloom+',
    upgradeDescription: 'Heal 20. +3 Regen.',
    baseHeal: 14,
    upgradedHeal: 20,
    isRare: true,
  },

  // ── Precision ───────────────────────────────────────────────────
  {
    id: 'r-double-tap',
    name: 'Double Tap',
    cost: 1,
    trait: 'precision',
    description: 'Deal 4 damage ×2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Double Tap+',
    upgradeDescription: 'Deal 6 damage ×2.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 'r-headshot',
    name: 'Headshot',
    cost: 2,
    trait: 'precision',
    description: 'Deal 14 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Headshot+',
    upgradeDescription: 'Deal 18 damage. Vuln 1.',
    baseDamage: 14,
    upgradedDamage: 18,
  },
  {
    id: 'r-volley',
    name: 'Volley',
    cost: 2,
    trait: 'precision',
    description: 'Deal 8 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Volley+',
    upgradeDescription: 'Deal 12 damage to all.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
  },
  {
    id: 'r-piercing-shot',
    name: 'Piercing Shot',
    cost: 1,
    trait: 'precision',
    description: 'Deal 7 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Piercing Shot+',
    upgradeDescription: 'Deal 10 damage.',
    baseDamage: 7,
    upgradedDamage: 10,
  },
  {
    id: 'r-rapid-fire',
    name: 'Rapid Fire',
    cost: 2,
    trait: 'precision',
    description: 'Deal 4 damage ×3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Rapid Fire+',
    upgradeDescription: 'Deal 6 damage ×3.',
    baseDamage: 4,
    upgradedDamage: 6,
  },
  {
    id: 'r-kill-shot',
    name: 'Kill Shot',
    cost: 3,
    trait: 'precision',
    description: 'Deal 22 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Kill Shot+',
    upgradeDescription: 'Deal 28 damage.',
    baseDamage: 22,
    upgradedDamage: 28,
    isRare: true,
  },
  {
    id: 'r-trick-shot',
    name: 'Trick Shot',
    cost: 1,
    trait: 'precision',
    description: 'Deal 6 damage. Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Trick Shot+',
    upgradeDescription: 'Deal 8 damage. Gain 5 Block.',
    baseDamage: 6,
    upgradedDamage: 8,
    baseBlock: 3,
    upgradedBlock: 5,
  },
  {
    id: 'r-hunters-mark',
    name: "Hunter's Mark",
    cost: 1,
    trait: 'precision',
    description: 'Deal 5 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: "Hunter's Mark+",
    upgradeDescription: 'Deal 8 damage. Vuln 2.',
    baseDamage: 5,
    upgradedDamage: 8,
  },
  {
    id: 'r-barrage',
    name: 'Barrage',
    cost: 3,
    trait: 'precision',
    description: 'Deal 6 damage ×4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Barrage+',
    upgradeDescription: 'Deal 8 damage ×4.',
    baseDamage: 6,
    upgradedDamage: 8,
    isRare: true,
  },
  {
    id: 'r-steady-aim',
    name: 'Steady Aim',
    cost: 0,
    trait: 'precision',
    description: 'Deal 2 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Steady Aim+',
    upgradeDescription: 'Deal 4 damage. Vuln 1.',
    baseDamage: 2,
    upgradedDamage: 4,
  },
  {
    id: 'r-critical-strike',
    name: 'Critical Strike',
    cost: 2,
    trait: 'precision',
    description: 'Deal 18 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Critical Strike+',
    upgradeDescription: 'Deal 24 damage.',
    baseDamage: 18,
    upgradedDamage: 24,
  },
  {
    id: 'r-deadeye',
    name: 'Deadeye',
    cost: 3,
    trait: 'precision',
    description: 'Deal 26 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Deadeye+',
    upgradeDescription: 'Deal 34 damage.',
    baseDamage: 26,
    upgradedDamage: 34,
    isRare: true,
  },

  // ── Venom ───────────────────────────────────────────────────────
  {
    id: 'r-venom-blade',
    name: 'Venom Blade',
    cost: 1,
    trait: 'venom',
    description: 'Deal 4 damage. Burn 5.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Venom Blade+',
    upgradeDescription: 'Deal 6 damage. Burn 8.',
    baseDamage: 4,
    upgradedDamage: 6,
    baseBurn: 5,
    upgradedBurn: 8,
  },
  {
    id: 'r-noxious-cloud',
    name: 'Noxious Cloud',
    cost: 2,
    trait: 'venom',
    description: 'Burn 6 to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Noxious Cloud+',
    upgradeDescription: 'Burn 9 to all.',
    baseBurn: 6,
    upgradedBurn: 9,
    isAoe: true,
  },
  {
    id: 'r-corrosion',
    name: 'Corrosion',
    cost: 1,
    trait: 'venom',
    description: 'Burn 4. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Corrosion+',
    upgradeDescription: 'Burn 7. Weak 1.',
    baseBurn: 4,
    upgradedBurn: 7,
  },
  {
    id: 'r-plague',
    name: 'Plague',
    cost: 3,
    trait: 'venom',
    description: 'Burn 8 to all. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Plague+',
    upgradeDescription: 'Burn 12 to all. Vuln 1.',
    baseBurn: 8,
    upgradedBurn: 12,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'r-envenom',
    name: 'Envenom',
    cost: 1,
    trait: 'venom',
    description: 'Deal 6 damage. Burn 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Envenom+',
    upgradeDescription: 'Deal 9 damage. Burn 5.',
    baseDamage: 6,
    upgradedDamage: 9,
    baseBurn: 3,
    upgradedBurn: 5,
  },
  {
    id: 'r-toxic-spray',
    name: 'Toxic Spray',
    cost: 2,
    trait: 'venom',
    description: 'Deal 4 damage to all. Burn 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Toxic Spray+',
    upgradeDescription: 'Deal 6 damage to all. Burn 6.',
    baseDamage: 4,
    upgradedDamage: 6,
    baseBurn: 4,
    upgradedBurn: 6,
    isAoe: true,
  },
  {
    id: 'r-festering-wound',
    name: 'Festering Wound',
    cost: 2,
    trait: 'venom',
    description: 'Deal 8 damage. Burn 6.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Festering Wound+',
    upgradeDescription: 'Deal 12 damage. Burn 8.',
    baseDamage: 8,
    upgradedDamage: 12,
    baseBurn: 6,
    upgradedBurn: 8,
  },
  {
    id: 'r-contaminate',
    name: 'Contaminate',
    cost: 0,
    trait: 'venom',
    description: 'Burn 3. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Contaminate+',
    upgradeDescription: 'Burn 5. Weak 1.',
    baseBurn: 3,
    upgradedBurn: 5,
  },
  {
    id: 'r-putrefy',
    name: 'Putrefy',
    cost: 2,
    trait: 'venom',
    description: 'Deal 10 damage. Burn 4.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Putrefy+',
    upgradeDescription: 'Deal 14 damage. Burn 6.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseBurn: 4,
    upgradedBurn: 6,
  },
  {
    id: 'r-bio-bomb',
    name: 'Bio Bomb',
    cost: 3,
    trait: 'venom',
    description: 'Deal 8 damage to all. Burn 8.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Bio Bomb+',
    upgradeDescription: 'Deal 12 damage to all. Burn 12.',
    baseDamage: 8,
    upgradedDamage: 12,
    baseBurn: 8,
    upgradedBurn: 12,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'r-miasma',
    name: 'Miasma',
    cost: 1,
    trait: 'venom',
    description: 'Weak 1. Vuln 1. Burn 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Miasma+',
    upgradeDescription: 'Weak 1. Vuln 1. Burn 4.',
    baseBurn: 2,
    upgradedBurn: 4,
  },
  {
    id: 'r-pandemic',
    name: 'Pandemic',
    cost: 3,
    trait: 'venom',
    description: 'Burn 12 to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Pandemic+',
    upgradeDescription: 'Burn 16 to all.',
    baseBurn: 12,
    upgradedBurn: 16,
    isAoe: true,
    isRare: true,
  },
];

export { REWARD_CARD_POOL };
