import type { Card } from '@/features/gameConfig/cardTypes';

const RANGER_STARTER: Card[] = [
  // Shadow (5)
  {
    id: 'r-shadow-mark',
    name: 'Shadow Mark',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 3 damage. Vuln 2 turns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Deep Mark',
    upgradeDescription: 'Deal 6 damage. Vuln 3 turns.',
    baseDamage: 3,
    upgradedDamage: 6,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 'r-ambush',
    name: 'Ambush',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 16 damage. +8 if Vuln.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ambush+',
    upgradeDescription: 'Deal 22 damage. +10 if Vuln.',
    baseDamage: 16,
    upgradedDamage: 22,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 'r-poison-arrow',
    name: 'Poison Arrow',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 7 damage. Burn 6.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Venom Arrow',
    upgradeDescription: 'Deal 10 damage. Burn 8.',
    baseDamage: 7,
    upgradedDamage: 10,
    baseBurn: 6,
    upgradedBurn: 8,
    starterRole: 'ranger',
  },
  {
    id: 'r-nick',
    name: 'Nick',
    cost: 0,
    trait: 'shadow',
    description: 'Deal 4 damage. Weaken 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Nick+',
    upgradeDescription: 'Deal 6 damage. Weaken 1. Vuln 1.',
    baseDamage: 4,
    upgradedDamage: 6,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_IceShard',
  },
  {
    id: 'r-smoke-bomb',
    name: 'Smoke Bomb',
    cost: 1,
    trait: 'shadow',
    description: 'Gain 8 Block. Weaken 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Smoke Bomb+',
    upgradeDescription: 'Gain 12 Block. Weaken 2.',
    baseBlock: 8,
    upgradedBlock: 12,
    starterRole: 'ranger',
  },
  // Nature (4)
  {
    id: 'r-vine-lash',
    name: 'Vine Lash',
    cost: 1,
    trait: 'nature',
    description: 'Deal 6 damage. Heal 8 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Vine Lash+',
    upgradeDescription: 'Deal 10 damage. Heal 12 HP.',
    baseDamage: 6,
    upgradedDamage: 10,
    baseHeal: 8,
    upgradedHeal: 12,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 'r-regrowth',
    name: 'Regrowth',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Regrowth+',
    upgradeDescription: 'Heal 10 HP. +1 Regen.',
    baseHeal: 6,
    upgradedHeal: 10,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 'r-thorn-burst',
    name: 'Thorn Burst',
    cost: 1,
    trait: 'nature',
    description: 'Deal 6 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Thorn Burst+',
    upgradeDescription: 'Deal 10 damage to all.',
    baseDamage: 6,
    upgradedDamage: 10,
    isAoe: true,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 'r-sprout',
    name: 'Sprout',
    cost: 0,
    trait: 'nature',
    description: 'Heal 2 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Sprout+',
    upgradeDescription: 'Heal 4 HP. +1 Regen.',
    baseHeal: 2,
    upgradedHeal: 4,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
  },
  // Fire (2)
  {
    id: 'r-flame-arrow',
    name: 'Flame Arrow',
    cost: 1,
    trait: 'fire',
    description: 'Deal 10 damage. Burn 5.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Flame Arrow+',
    upgradeDescription: 'Deal 14 damage. Burn 7.',
    baseDamage: 10,
    upgradedDamage: 14,
    baseBurn: 5,
    upgradedBurn: 7,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_fireball',
  },
  {
    id: 'r-volley',
    name: 'Volley',
    cost: 2,
    trait: 'fire',
    description: 'Deal 14 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Volley+',
    upgradeDescription: 'Deal 20 damage to all.',
    baseDamage: 14,
    upgradedDamage: 20,
    isAoe: true,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_Fireball',
  },
  // Guard (1)
  {
    id: 'r-dodge',
    name: 'Dodge',
    cost: 0,
    trait: 'guard',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Dodge+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
    starterRole: 'ranger',
  },
  // Storm (1)
  {
    id: 'r-quick-shot',
    name: 'Quick Shot',
    cost: 0,
    trait: 'storm',
    description: 'Deal 4 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Quick Shot+',
    upgradeDescription: 'Deal 6 damage. +1 energy if chained.',
    baseDamage: 4,
    upgradedDamage: 6,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_IceShard',
  },
  // Neutral (2)
  {
    id: 'r-snipe',
    name: 'Snipe',
    cost: 3,
    trait: 'neutral',
    description: 'Deal 30 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Snipe+',
    upgradeDescription: 'Deal 40 damage.',
    baseDamage: 30,
    upgradedDamage: 40,
    starterRole: 'ranger',
  },
  {
    id: 'r-focus',
    name: 'Focus',
    cost: 1,
    trait: 'neutral',
    description: 'Transform into random card.',
    upgraded: false,
    upgradeThreshold: 99,
    upgradeName: 'Focus+',
    upgradeDescription: 'Transform. Costs 0.',
    starterRole: 'ranger',
  },
];

export { RANGER_STARTER };
