import type { Card } from '@/features/gameConfig/cardTypes';

const SAGE_STARTER: Card[] = [
  // Fire (5)
  {
    id: 's-fireball',
    name: 'Fireball',
    cost: 1,
    trait: 'fire',
    description: 'Deal 12 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Fireball+',
    upgradeDescription: 'Deal 16 damage. +1 Fire charge.',
    baseDamage: 12,
    upgradedDamage: 16,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
  },
  {
    id: 's-scorch',
    name: 'Scorch',
    cost: 1,
    trait: 'fire',
    description: 'Deal 8 damage. Burn 7.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Scorch+',
    upgradeDescription: 'Deal 12 damage. Burn 10.',
    baseDamage: 8,
    upgradedDamage: 12,
    baseBurn: 7,
    upgradedBurn: 10,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
  },
  {
    id: 's-wildfire',
    name: 'Wildfire',
    cost: 2,
    trait: 'fire',
    description: 'Deal 18 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Wildfire+',
    upgradeDescription: 'Deal 24 damage to all.',
    baseDamage: 18,
    upgradedDamage: 24,
    isAoe: true,
    starterRole: 'sage',
  },
  {
    id: 's-ignite',
    name: 'Ignite',
    cost: 0,
    trait: 'fire',
    description: 'Deal 5 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ignite+',
    upgradeDescription: 'Deal 8 damage. Burn 4.',
    baseDamage: 5,
    upgradedDamage: 8,
    upgradedBurn: 4,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
  },
  {
    id: 's-flame-lance',
    name: 'Flame Lance',
    cost: 2,
    trait: 'fire',
    description: 'Deal 16 damage. Burn 6.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Flame Lance+',
    upgradeDescription: 'Deal 22 damage. Burn 8.',
    baseDamage: 16,
    upgradedDamage: 22,
    baseBurn: 6,
    upgradedBurn: 8,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
  },
  // Storm (4)
  {
    id: 's-zap',
    name: 'Zap',
    cost: 0,
    trait: 'storm',
    description: 'Deal 4 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Zap+',
    upgradeDescription: 'Deal 6 damage. +1 energy if chained.',
    baseDamage: 4,
    upgradedDamage: 6,
    starterRole: 'sage',
  },
  {
    id: 's-arc-bolt',
    name: 'Arc Bolt',
    cost: 2,
    trait: 'storm',
    description: 'Deal 14 damage. +1 energy.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Arc Bolt+',
    upgradeDescription: 'Deal 20 damage. +1 energy.',
    baseDamage: 14,
    upgradedDamage: 20,
    starterRole: 'sage',
  },
  {
    id: 's-chain-spark',
    name: 'Chain Spark',
    cost: 1,
    trait: 'storm',
    description: 'Deal 8 damage. +1 energy if chained.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Chain Lightning',
    upgradeDescription: 'Deal 12 damage. +1 energy.',
    baseDamage: 8,
    upgradedDamage: 12,
    starterRole: 'sage',
  },
  {
    id: 's-static-field',
    name: 'Static Field',
    cost: 1,
    trait: 'storm',
    description: 'Deal 6 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Static Field+',
    upgradeDescription: 'Deal 10 damage to all.',
    baseDamage: 6,
    upgradedDamage: 10,
    isAoe: true,
    starterRole: 'sage',
  },
  // Nature (2)
  {
    id: 's-ice-shield',
    name: 'Ice Shield',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ice Shield+',
    upgradeDescription: 'Heal 10 HP.',
    baseHeal: 6,
    upgradedHeal: 10,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_GreenTest',
  },
  {
    id: 's-mana-bloom',
    name: 'Mana Bloom',
    cost: 0,
    trait: 'nature',
    description: 'Heal 2 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Mana Bloom+',
    upgradeDescription: 'Heal 4 HP. +1 Regen.',
    baseHeal: 2,
    upgradedHeal: 4,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_GreenTest',
  },
  // Guard (1)
  {
    id: 's-arcane-ward',
    name: 'Arcane Ward',
    cost: 0,
    trait: 'guard',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Arcane Ward+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
    starterRole: 'sage',
  },
  // Shadow (1)
  {
    id: 's-hex',
    name: 'Hex',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 5 damage. Vuln 2 turns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Hex+',
    upgradeDescription: 'Deal 8 damage. Vuln 3 turns.',
    baseDamage: 5,
    upgradedDamage: 8,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_IceShard',
  },
  // Neutral (2)
  {
    id: 's-haymaker',
    name: 'Haymaker',
    cost: 3,
    trait: 'neutral',
    description: 'Deal 28 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Haymaker+',
    upgradeDescription: 'Deal 36 damage.',
    baseDamage: 28,
    upgradedDamage: 36,
    starterRole: 'sage',
  },
  {
    id: 's-focus',
    name: 'Focus',
    cost: 1,
    trait: 'neutral',
    description: 'Transform into random card.',
    upgraded: false,
    upgradeThreshold: 99,
    upgradeName: 'Focus+',
    upgradeDescription: 'Transform. Costs 0.',
    starterRole: 'sage',
  },
];

export { SAGE_STARTER };
